"""Collect notices from the exact Cargo.lock graph, including all platforms.

Run cargo metadata --locked --format-version 1 into a temporary JSON file, then
pass that file here. Registry sources must already be downloaded by Cargo.
"""
import argparse
import hashlib
import json
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[1]


def lockfile_fingerprint(content: bytes) -> str:
    # Git may check text out with CRLF on Windows. Keep dependency-content
    # changes significant without making the notices depend on core.autocrlf.
    return hashlib.sha256(content.replace(b"\r\n", b"\n")).hexdigest()


def generate(metadata: dict) -> str:
    lock_bytes = (ROOT / "Cargo.lock").read_bytes()
    locked = {
        (p["name"], p["version"], p["source"])
        for p in tomllib.loads(lock_bytes.decode())["package"]
        if "source" in p
    }
    packages = sorted(
        (p for p in metadata["packages"] if p["source"]),
        key=lambda p: (p["name"], p["version"], p["source"]),
    )
    if {(p["name"], p["version"], p["source"]) for p in packages} != locked:
        raise ValueError("metadata does not cover the complete locked dependency graph")
    texts = {}
    sections = []
    for package in packages:
        root = Path(package["manifest_path"]).parent
        files = sorted(
            p for p in root.rglob("*") if p.is_file()
            and any(word in p.name.lower() for word in ("license", "copying", "notice", "copyright"))
        )
        if package.get("license_file"):
            extra = root / package["license_file"]
            if extra not in files:
                files.append(extra)
        if not files:
            raise ValueError(f"no license text found for {package['name']}")
        section = [
            f"{package['name']} {package['version']}",
            f"Declared license: {package['license'] or 'see license file'}",
            f"Source: {package['source']}",
        ]
        for path in files:
            content = path.read_text(encoding="utf-8").strip()
            if not content:
                raise ValueError(f"empty license file: {path}")
            digest = hashlib.sha256(content.encode()).hexdigest()
            if digest not in texts:
                texts[digest] = (len(texts) + 1, content)
            section.append(f"  {path.relative_to(root).as_posix()}: Text {texts[digest][0]}")
        sections.append("\n".join(section))
    header = (
        "Third-party dependency notices for Vex\n"
        "=====================================\n\n"
        f"Cargo.lock SHA-256 (LF): {lockfile_fingerprint(lock_bytes)}\n\n"
        "Generated by tools/dependency_notices.py from Cargo's locked package sources.\n"
        "Includes build-time and platform-specific dependencies; a given binary may\n"
        "use only a subset. Identical license texts are shared by reference below.\n"
        "These notices do not change the upstream license choices.\n"
        "Unmodified package sources are available from crates.io by name and version.\n\n"
    )
    return header + "\n\n".join(sections) + "\n\n" + "\n\n".join(
        f"Text {number}\n{'=' * 72}\n{content}"
        for number, content in texts.values()
    ) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("metadata", type=Path)
    args = parser.parse_args()
    output = generate(json.loads(args.metadata.read_text(encoding="utf-8")))
    (ROOT / "THIRD_PARTY_LICENSES").write_text(output, encoding="utf-8", newline="\n")
